name: Run Postman Tests

on:
  push:
    branches: ['*']
  pull_request:
    branches: ['*']

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Newman
        run: npm install -g newman

      - name: Build Spring Boot backend
        run: mvn clean install -DskipTests
        working-directory: IoHome/backend


      - name: Start backend in background
        run: |
           nohup mvn spring-boot:run &> spring.log &
            sleep 30
        working-directory: IoHome/backend    

      - name: Run Postman tests
        run: |
          newman run IoHome/test/IoHome.postman_collection.json \
            --environment IoHome/test/IoHome.postman_environment.json \
            --reporters cli,json \
            --reporter-json-export loHome/test/report.json

      - name: Upload Newman Report
        uses: actions/upload-artifact@v4
        with:
          name: newman-report
          path: loHome/test/report.json
