name: Run Selenium IDE Tests on Firefox

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]
  workflow_dispatch:

jobs:
  selenium-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install selenium-side-runner
      run: npm install -g selenium-side-runner

    - name: Install Firefox and Geckodriver
      run: |
        sudo apt-get update
        sudo apt-get install -y firefox
        GECKO_VERSION=v0.36.0
        wget https://github.com/mozilla/geckodriver/releases/download/${GECKO_VERSION}/geckodriver-${GECKO_VERSION}-linux64.tar.gz
        tar -xzf geckodriver-${GECKO_VERSION}-linux64.tar.gz
        chmod +x geckodriver
        sudo mv geckodriver /usr/local/bin/

    - name: Create selenium.config.js
      run: |
        echo "module.exports = { browsers: [{ browserName: 'firefox' }] };" > selenium.config.js

    - name: Run Selenium tests on Firefox
      run: selenium-side-runner IoHome/test/IoHome.side
