name: Run Selenium IDE Tests on Firefox

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  selenium-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install selenium-side-runner
      run: npm install -g selenium-side-runner

    - name: Install Firefox and GeckoDriver
      run: |
        sudo apt-get update
        sudo apt-get install -y firefox
        wget https://github.com/mozilla/geckodriver/releases/latest/download/geckodriver-linux64.tar.gz
        tar -xzf geckodriver-linux64.tar.gz
        sudo mv geckodriver /usr/local/bin/

    - name: Run Selenium tests on Firefox
      run: selenium-side-runner --browser firefox IoHome/test/IoHome.side
